name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npm run affected-build

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: garretpremo/test-nx-angular
          tags: |
            type=raw,value=latest
            type=raw,value=build-${{github.run_number}}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          file: ./.github/workflows/Dockerfile
          context: ./dist/test-nx-angular/browser
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
